### ISSUE TITLE
添加文件 a.txt

### ISSUE THREAD

**Issue by tangtongwch** [tangtongwch/work#1]

**Comment by tangtonggit** [comment]
-[ ] 实验9 [交叉连接] SELECT pt.name, p.product_cd, p.name FROM product p CROSS JOIN product_type pt;返回结果的图片不正确

**Comment by tangtonggit** [comment]
- [ ] 实验9 [交叉连接] SELECT pt.name, p.product_cd, p.name FROM product p CROSS JOIN product_type pt;返回结果的图片不正确

**Comment by tangtonggit** [comment]
-[ ]- 实验13 [连接分区数据]  报错：Table 'bank.transaction_historic' doesn't exist   原因 bank数据库中不包含transaction_historic表
![13_1](https://user-images.githubusercontent.com/52146856/90584499-5101ae80-e205-11ea-8cca-410477f72b52.png)
![13_2](https://user-images.githubusercontent.com/52146856/90584655-ab027400-e205-11ea-9b88-f66387bb98f5.png)
